//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryMarketplace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int BookingID { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        [Required]
        [Display(Name = "Pickup Address:")]
        public string PickupAddress { get; set; }
        [Required]
        [Display(Name = "Delivery Address:")]
        public string DeliveryAddress { get; set; }
        [Required]
        [Display(Name = "Pickup Location:")]
        public string PickupLoc { get; set; }
        [Required]
        [Display(Name = "Delivery Location:")]
        public string DeliverLoc { get; set; }
        [Required]
        [Display(Name = "Status:")]
        public string Status { get; set; }
        [Required]
        [Display(Name = "Price($):")]
        public decimal Price { get; set; }
        public Nullable<int> DriverID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}