//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryMarketplace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public int UserID { get; set; }
        [Required]
        [Display(Name = "Feedback:")]
        public string Feedback1 { get; set; }
    
        public virtual User User { get; set; }
    }
}
